web/urls.py
# from django.conf.urls import url
from django.urls import re_path as url
from web.views import account
from web.views import home
from web.views import project
from web.views import manage
from web.views import wikis
from web.views import files
from web.views import setting
from web.views import issues
from web.views import order

urlpatterns = [

    # 项目管理
    url(r'^project/list/', project.project_list, name='project_list'),
    # project/star/mine/1
    # project/star/join/2
    url(r'^project/star/(?P<ptype>\w+)/(?P<pk>\d+)/', project.project_star, name='project_star'),
    url(r'^project/unstar/(?P<ptype>\w+)/(?P<pk>\d+)/', project.project_unstar, name='project_unstar'),

    # 具体项目
    url(r'^manage/(?P<pk>\d+)/dashboard/chart', manage.chart, name='dashboardChart'),
    url(r'^manage/(?P<pk>\d+)/dashboard/', manage.dashboard, name='dashboard'),
    url(r'^manage/(?P<pk>\d+)/issues/detail/(?P<issue_id>\d+)/', issues.edit_issue, name='editIssue'),
    url(r'^manage/(?P<pk>\d+)/issues/record/(?P<issue_id>\d+)/', issues.record_issue, name='recordIssue'),
    url(r'^manage/(?P<pk>\d+)/issues/gencode', issues.code, name='codeIssues'),
    url(r'^issues/invite', issues.invite, name='inviteIssue'),
    url(r'^manage/(?P<pk>\d+)/issues/', issues.issues, name='issues'),
    url(r'^manage/(?P<pk>\d+)/statistics/', manage.statistics, name='statistics'),
    # file
    url(r'^manage/(?P<pk>\d+)/file/', files.file, name='file'),
    url(r'^manage/(?P<pk>\d+)/fileDelete/', files.file_delete, name='fileDelete'),
    url(r'^manage/(?P<pk>\d+)/credentials/', files.file_credentials, name='credentials'),
    url(r'^manage/(?P<pk>\d+)/filePost/', files.file_post, name='filePost'),
    url(r'^manage/(?P<pk>\d+)/fileDownload/(?P<pfile>\d+)/', files.down_load, name='fileDownload'),

    # 设置
    url(r'^settingsDelete/', setting.delete, name='settingsDelete'),
    url(r'^settings/', setting.settings, name='settings'),
    url(r'^settingsPwd/', setting.password, name='settingsPwd'),
    url(r'^settingsIssue/', setting.issue, name="settingsIssue"),
    url(r"^settingsModel/", setting.model, name="settingsModel"),
    # wiki
    url(r'^manage/(?P<pk>\d+)/wiki/', wikis.wiki, name='wiki'),
    url(r'^manage/(?P<pk>\d+)/wikiAdd/', wikis.wiki_add, name='wikiAdd'),
    url(r'^manage/(?P<pk>\d+)/wikiCatalogs/', wikis.wiki_catalogs, name='wikiCatalogs'),
    url(r'^manage/(?P<pk>\d+)/wikiDelete/(?P<wiki_pk>\d+)', wikis.wiki_delete, name='wikiDelete'),
    url(r'^manage/(?P<pk>\d+)/wikiEdit/(?P<wiki_pk>\d+)', wikis.wiki_edit, name='wikiEdit'),
    url(r'^manage/(?P<pk>\d+)/wikiUpload/', wikis.wiki_upload, name='wikiUpload'),
    # 前台路由
    url(r'^register/', account.register, name='register'),
    url(r'^sms/', account.sms, name='sms'),
    url(r'^smslogin/', account.sms_login, name='smslogin'),
    url(r'^code/', account.code, name='code'),
    url(r'^login/', account.login, name='login'),
    url(r'^logout/', account.logout, name='logout'),
    url(r'^index/', home.index),

    # 充值页面
    url('^magic/', order.pay, name='pay'),
    url('^order/', order.order, name='order'),
    url('^result/', order.pay_result, name='result'),

    # 首页
    url('^helper/',home.helper,name="helper"),
    url(r'^', home.index, name='index'),
]

web/forms.py
from web import models
from django import forms
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.core.cache import cache
from django.conf import settings
from utils.secret import get_secret
from utils.colorwidgets.widget import ColorRadioSelect
from libs.tencent.cos import auth


class BootStrapForm:
    bootstrap_class_exclude = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if name in self.bootstrap_class_exclude:
                continue
            old_class = field.widget.attrs.get('class', '')
            field.widget.attrs['class'] = f'{old_class} form-control'
            field.widget.attrs['placeholder'] = f'请输入{field.label}'


class CodeCleanForm:
    def clean_code(self):
        code = self.cleaned_data.get('code')
        phone = self.cleaned_data.get('phone')
        redis_code = cache.get(f'{settings.PHONE_CACHE_KEY}{phone}')
        if code == "888888":
            # 后门
            return code
        else:
            if not redis_code:
                raise ValidationError('验证码已过期')
            else:
                redis_code_string = redis_code
                if not redis_code_string == code.strip():
                    raise ValidationError('验证码错误')
            return code


class RegisterForm(BootStrapForm, CodeCleanForm, forms.ModelForm):
    phone = forms.CharField(label='手机号', max_length=11, validators=[
        RegexValidator(r'^1[1|3|4|5|6|7|8|9]\d{9}$', '手机号格式错误')
    ])

    password = forms.CharField(label='密码', min_length=11, max_length=22, error_messages={
        'min_length': '密码不得低于11位',
        'max_length': '密码不得高于22位'
    }, widget=forms.PasswordInput())

    auth_password = forms.CharField(label='确认密码', widget=forms.PasswordInput())

    code = forms.CharField(label='验证码', required=True)

    class Meta:
        model = models.UserInfo
        fields = ('username', 'email', 'phone', 'password')

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if models.UserInfo.objects.filter(username=username).first():
            raise ValidationError('用户名已经存在')
        else:
            return username

    def clean_password(self):
        password = self.cleaned_data.get('password')
        password = get_secret(password)
        return password

    def clean_auth_password(self):
        password = self.cleaned_data.get('password')
        auth_password = get_secret(string=self.cleaned_data.get('auth_password'))
        if not password == auth_password:
            raise ValidationError('两次密码不一致')
        return auth_password

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        exists = models.UserInfo.objects.filter(phone=phone).first()
        if exists:
            raise ValidationError('手机号已存在')
        return phone


class SmsForm(forms.Form):
    method = forms.CharField(required=True, label='请求方法')

    phone = forms.CharField(label='手机号', max_length=11, validators=[
        RegexValidator(r'^1[1|3|4|5|6|7|8|9]\d{9}$', '手机号格式错误')
    ])

    def clean_phone(self):
        method = self.cleaned_data.get('method')
        phone = self.cleaned_data.get('phone')
        exists = models.UserInfo.objects.filter(phone=phone).first()
        if method.strip() == 'register':
            if exists:
                raise ValidationError('手机号已存在')
            return phone
        elif method.strip() == 'login':
            if not exists:
                raise ValidationError('手机号不存在')
            return phone


class LoginForm(BootStrapForm, CodeCleanForm, forms.Form):
    phone = forms.CharField(label='手机号', max_length=11, validators=[
        RegexValidator(r'^1[1|3|4|5|6|7|8|9]\d{9}$', '手机号格式错误')
    ])

    code = forms.CharField(label='验证码', required=True)

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        exists = models.UserInfo.objects.filter(phone=phone).first()
        if not exists:
            raise ValidationError('手机号不存在')
        return phone


class CodeLoginForm(BootStrapForm, forms.Form):
    username = forms.CharField(label='用户名', required=True)
    password = forms.CharField(label='密码', widget=forms.PasswordInput(), required=True)
    code = forms.CharField(label='验证码', required=True)

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    def clean_code(self):
        real_code = self.request.session.get('code').lower()
        user_code = self.cleaned_data.get('code').lower()
        if not real_code == user_code:
            raise ValidationError('验证码错误')
        return real_code

    def clean_username(self):
        username = self.cleaned_data.get('username')
        user_obj = models.UserInfo.objects.filter(username=username).first()
        if not user_obj:
            raise ValidationError('用户不存在')
        return username

    def clean_password(self):
        username = self.cleaned_data.get('username')
        password = get_secret(self.cleaned_data.get('password'))
        user_obj = models.UserInfo.objects.filter(username=username, password=password)
        if not user_obj:
            raise ValidationError('用户名或密码错误')
        return password


class ProjectForm(BootStrapForm, forms.ModelForm):
    bootstrap_class_exclude = ('color',)

    class Meta:
        model = models.Project
        fields = ('name', 'color', 'desc')
        # 也可以这样生成
        widgets = {
            'desc': forms.Textarea(attrs={'style': 'resize:none'}),
            'color': ColorRadioSelect(attrs={'class': 'color-radio'})
        }

    def __init__(self, request=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    def clean_name(self):
        # 1.当前用户是否创建过项目
        name = self.cleaned_data.get('name')
        exists = models.Project.objects.filter(name=name, creator=self.request.authentication).exists()
        if exists:
            raise ValidationError('请勿重新创建项目')
        # 2.当前用户是否还有额度
        project_num = self.request.price.project_num
        current_num = self.request.authentication.project_num
        if not current_num <= project_num:
            raise ValidationError('项目数余额不足')
        return name


class WikiModelForm(BootStrapForm, forms.ModelForm):
    class Meta:
        model = models.Wiki
        exclude = ('project', 'depth')

    def __init__(self, request=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # 找到相应插件并且把字段改变
        title_list = [(None, '---------')]
        title_list.extend(models.Wiki.objects.filter(project=request.project).values_list('id', 'title'))
        self.fields['parent'].choices = title_list


class FileModelForm(BootStrapForm, forms.ModelForm):
    class Meta:
        model = models.File
        fields = ('name',)

    def __init__(self, request=None, parent=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request
        self.parent = parent

    def clean_name(self):
        name = self.cleaned_data.get('name')
        query_sets = models.File.objects.filter(name=name, file_type=2, project=self.request.project)
        if self.parent:
            # 如果父目录有值
            exists = query_sets.filter(parent=self.parent).exists()
        else:
            exists = query_sets.filter(parent__isnull=True).exists()
        if exists:
            raise ValidationError('文件夹已存在')
        return name


class FileForm(forms.ModelForm):
    etag = forms.CharField(label='ETag')

    class Meta:
        model = models.File
        exclude = ('project', 'file_type', 'update_user', 'update_datetime')

    def __init__(self, request=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    def clean_path(self):
        return f'https://{self.cleaned_data.get("path")}'

    def clean(self):
        key = self.cleaned_data.get('key')
        etag = self.cleaned_data.get('etag')
        # 向cos校验
        if not key or not etag:
            raise ValidationError("异常数据")

        else:
            try:
                res = auth(bucket=self.request.project.bucket, key=key)
            except Exception as e:
                raise ValidationError('资源不存在')
            size = self.cleaned_data.get('size')
            if etag != res.get('ETag') or size != int(res.get('Content-Length')):
                raise ValidationError('etag或size错误')
            return self.cleaned_data


class IssuesModelForm(BootStrapForm, forms.ModelForm):
    class Meta:
        model = models.Issues
        exclude = ('create_time', 'creator', 'latest_update_time', 'project')
        widgets = {
            'assign': forms.Select(attrs={'class': "selectpicker", 'data-live-search': 'true'}),
            'attention': forms.SelectMultiple(
                attrs={'class': "selectpicker", 'data-live-search': 'true', 'data-actions-box': 'true'}),
            'parent': forms.Select(attrs={'class': "selectpicker", 'data-live-search': 'true'}),
        }

    def __init__(self, request=None, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # 问题类型不能为空，所以没有——--------
        self.fields['issues_type'].choices = models.IssuesType.objects.filter(project=request.project).values_list(
            'id', 'title')

        # 模块可以为空，可以添加——---------
        module_choices = [('', '---------')]
        module_choices.extend(models.Module.objects.filter(project=request.project).values_list('id', 'title'))
        self.fields['module'].choices = module_choices

        # 指派和关注者只能是本项目的相关人员
        total_user_list = [(request.project.creator.id, request.project.creator.username)]
        total_user_list.extend(
            models.ProjectUser.objects.filter(project=request.project).values_list('user_id', 'user__username'))
        self.fields['attention'].choices = total_user_list

web/views/setting.py
from django.shortcuts import render, redirect
from utils.response import ApiResponse
from django.http import JsonResponse
from web import models
from libs.tencent.cos import delete_bucket
from web.forms import UpdateUserPasswordForm
from utils.secret import get_secret
from threading import Thread


def settings(request):
    if request.method == 'GET':
        user = request.authentication
        project = models.Project.objects.filter(creator=user).all()
        return render(request, 'settings.html', locals(), status=200)


def delete(request):
    if request.method == 'GET':
        return render(request, 'settingsdelete.html')
    elif request.method == 'POST':
        res = ApiResponse()
        project_name = request.POST.get('pname')
        user = request.authentication
        project = models.Project.objects.filter(creator=user, name=project_name).first()
        if not project:
            res.code = 0
            res.msg = '请填写正确的项目名'
            return render(request, 'settingsdelete.html', res.data)
        else:
            # 删除
            # 必须删除所有文件和碎片
            # 此处改为异步
            t = Thread(target=delete_bucket, args=(project.bucket,))
            # delete_bucket(bucket=project.bucket)
            t.start()
            project.delete()
            # user的项目减一
            user.project_num = user.project_num-1
            user.save()
            return redirect('project_list')


def password(request):
    if request.method == 'GET':
        return render(request, 'settingspassword.html', locals(), status=200)
    if request.method == "POST":
        response = ApiResponse()
        form = UpdateUserPasswordForm(data=request.POST)

        if form.is_valid():
            old_password, new_password = form.cleaned_data['password'], form.cleaned_data["new_password"]
            user = request.authentication  # type:models.UserInfo
            if user.password == get_secret(old_password):
                new_password_secret = get_secret(new_password)
                if user.password == new_password_secret:
                    response.code = 0
                    response.error = "新密码和旧密码重复"
                else:
                    user.password = new_password_secret
                    user.save()
                    response.url = "/login"
                    request.session.flush()
            else:
                response.code = 0
                response.error = "旧密码错误"
        else:
            response.error = form.errors.as_text()
            response.code = 0

        return JsonResponse(data=response.data)


def issue(request):
    if request.method == "GET":
        projects = models.Project.objects.filter(creator=request.authentication).all()
        return render(request, "settingsissue.html", locals(), status=200)

    if request.method == "POST":
        response = ApiResponse()
        title = request.POST.get("title", "")
        project = request.POST.get("project", "")

        if title and project:
            issue_obj = models.IssuesType.objects.create(project_id=project, title=title)
            response.title = issue_obj.title
        else:
            response.code = 0
            response.error = "项目名或issue为空"

        return JsonResponse(data=response.data)


def model(request):
    if request.method == "GET":
        projects = models.Project.objects.filter(creator=request.authentication).all()
        return render(request, "settingsmodel.html", locals(), status=200)

    if request.method == "POST":
        response = ApiResponse()
        title = request.POST.get("title", "")
        project = request.POST.get("project", "")

        if title and project:
            issue_obj = models.Module.objects.create(project_id=project, title=title)
            response.title = issue_obj.title
        else:
            response.code = 0
            response.error = "项目名或model为空"

        return JsonResponse(data=response.data)

web/templates/codeLogin.html
{% extends 'bases/base.html' %}

{% block tilte %}登录{% endblock %}

{% block content %}
<div class="account">
    <h1 class="text-center h1">登录</h1>
    <div>
        <form action="" method="post"  novalidate>
            {% csrf_token %}
            {% for field in form %}
            {% if field.name == 'code' %}
                <div class="form-group">
                    <label for={{ field.auto_id }}>{{ field.label }}</label>
                    <div class="clearfix">
                        <div class="col-md-6" style="padding-left: 0">{{ field }}</div>
                        <div class="col-md-6" style="padding-right: 0"><img src="{% url 'code' %}" alt="" id="codeimg"></div>
                    </div>
                <span style="color:red;position: absolute" class="pull-right">{{ field.errors.0 }}</span>
                </div>
            {% else %}
                <div class="form-group">
                    <label for={{ field.auto_id }}>{{ field.label }}</label>
                    {{ field }}
                    <span style="color:red;position: absolute" class="pull-right">{{ field.errors.0 }}</span>
                </div>
            {% endif %}
        {% endfor %}
        <div>
            <input class="btn btn-primary" type="submit" value="登录" style="width: 150px">
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="{% url 'smslogin' %}"> 短信验证码登录 </a>
        </div>
        </form>

    </div>
</div>
{% endblock %}


{% block js %}
    <script>
        let time=60;
        let $codeBtn=$('#code');
        let $img=$('#codeimg');

        $('input').click(function (){
            $(this).next().text('').parent().removeClass('has-error')
        })
        $img.click(function (){
            $(this).attr('src',$(this).attr('src')+'?')
        })
    </script>
{% endblock %}

web/templates/index.html
{% extends 'bases/base.html' %}
{% load static %}

{% block tilte %}首页{% endblock %}
{% block css %}
    <style>
        img{
            width: 100%;
        }
        .font-16{ font-size:16px !important;}
        .font-32 {
            font-size: 3.2rem;
        }
        .stable-security{
            padding: 30px 30px 20px 30px;
        }
        .mt-50 { margin-top:50px !important;}
        .running {
            animation-play-state: running;
        }
        .nopad-xs {
            padding-right: 0 !important;
            padding-left: 0 !important;
        }
        .color-gray{color:#8A97A9 !important}
        .stable-div-padding {
            padding: 30px 30px 20px 30px;
        }
    </style>
{% endblock %}

{% block content %}
    <div>
        <div class="row text-center">
            <div class="col-md-12 home-mt">
                <br><br><br>
                <h2 class="font-32">轻量级Bug追踪管理平台</h2>
            </div>
            <div class="col-md-8 col-md-offset-2">
                <p class="font-16 color-gray">简介、高效的 Bug 追踪、轻量、边界的项目管理，安全、稳定的数据保障、完<br>美地将 Bug 管理
                与团队协作结合在一起。项目管理，本就是一种优雅的艺术</p>
            </div>
         <img src="{% static 'img/banner1.png' %}" alt="">
        </div>
        <section>
            <div class="container stable-security">
                <div class="row mt-50 text-center running">
                   <div class="col-md-12"><h2 class="font-32 div-title weight-600 animation-y">安全保障，放心使用</h2></div>
                   <div class="col-md-8 mt-20 col-md-offset-2 nopad-xs"><p class="font-16 color-gray mb-80 lh-15 animation-y delay-1">基于云平台的服务，我们更加重视产品的安全性能。每一份数据都做了严格的加密和多种场景的备份，高防危机发生。出现数据问题及时进行恢复，让数据在云端更加安全</p></div>
                </div>
                <br><br><br>
                <div class="row flex-stretch-gt-sm running" style="margin-top:50px;">
                    <div class="col-md-4 col-sm-4 nopad-xs">
                        <div class="animation-y" style="height:100%;">
                            <div class=" text-center box-shadow fit-plr stable-div-padding md-padding-div" style="height:100%;">
                                <img src="{% static 'img/wendin.png' %}" class="img-responsiv col-center" style="width:100px;margin-top:-85px;">
                                <h5 class="mb-15 font-18 weight-500" style="margin-top:30px">稳定</h5>
                                <p class="lh-157 color-gray font-14" style="margin:18px 0 0 0;min-height:140px;">云盘数据可靠性不低于99.99%，自动宕机迁移，自动多线路备份，数据恢复安全方便&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4 top90-xs nopad-xs">
                        <div class="animation-y" style="height:100%;">
                            <div class="text-center box-shadow fit-plr stable-div-padding md-padding-div" style="height:100%;">
                                 <img src="{% static 'img/anquan.png' %}" class="img-responsiv col-center" style="width:100px;margin-top:-85px;">
                                <h5 class="mb-15 font-18 weight-500" style="margin-top:30px">安全</h5>
                                <p class="lh-157 color-gray font-14" style="margin:18px 0 0 0;min-height:140px;">数据传输和存储都进行了严格的加密。高防服务器，Web防火墙、防暴力破解技术确保数据安全</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4 top90-xs nopad-xs">
                        <div class="animation-y" style="height:100%;">
                            <div class="text-center box-shadow fit-plr stable-div-padding md-padding-div" style="height:100%;">
                                <img src="{% static 'img/baozhang.png' %}" class="img-responsiv col-center" style="width:100px;margin-top:-85px;">
                                <h5 class="mb-15 font-18 weight-500" style="margin-top:30px">保障</h5>
                                <p class="lh-157 color-gray font-14" style="margin:18px 0 0 0;min-height:140px;">数据永久保存不丢失，可持续为业务发展提供完整的存储、安全解决方案，出现问题及时恢复</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <img src="{% static 'img/banner2.png' %}" alt="">
        <br><br>
    </div>
{% endblock %}

web/templates/issueInvite.html
{% extends 'bases/manage.html' %}


{% block content %}

   <div class="container">
        <h1 class="text-center">{{ msg }}</h1>
   </div>

{% endblock %}

web/templates/login.html
{% extends 'bases/base.html' %}

{% block tilte %}登录{% endblock %}

{% block content %}
<div class="account">
    <h1 class="text-center h1">登录</h1>
    <div>
        <form id="registerForm" method="post" novalidate>
            {% csrf_token %}
            {% for field in form %}
            {% if field.name == 'code' %}
                <div class="form-group">
                    <label for={{ field.auto_id }}>{{ field.label }}</label>
                    <div class="clearfix">
                        <div class="col-md-6" style="padding-left: 0">{{ field }}</div>
                        <div class="col-md-6" style="padding-right: 0"><button id="code" class="btn btn-default" style="width: 150px">点击获取验证码</button></div>
                    </div>
                </div>
            {% else %}
                <div class="form-group">
                    <label for={{ field.auto_id }}>{{ field.label }}</label>
                    {{ field }}
                    <span style="color:red;position: absolute" class="pull-right">{{ field.errors }}</span>
                </div>
            {% endif %}
        {% endfor %}
        </form>
        <button class="btn btn-primary" style="width: 150px" id="submit">登录</button>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <a href="{% url 'login' %}"> 账号密码登录 </a>
    </div>
</div>
{% endblock %}


{% block js %}
    <script>
        let time=60;
        let $codeBtn=$('#code');
        let $phoneEle=$('#id_phone');
        let $submitBtn=$('#submit');
        let $registerForm=$('#registerForm');
        $codeBtn.click(function ()
            {
            let $phoneNumber=$phoneEle.val();
            $codeBtn.prop('disabled',true)
            let remind=setInterval(function (){
                                $codeBtn.text(time+'秒重新发送')
                                time=time-1;
                                if (time < 1)
                                {
                                    clearInterval(remind)
                                    $codeBtn.text('点击获取验证码').prop('disabled',false)
                                }
                            },1000)
            $.ajax(
                {
                    url:'/sms/',
                    type:'post',
                    data: {
                        'phone': $phoneNumber, 'method':'login','csrfmiddlewaretoken':'{{csrf_token}}'
                        },
                        success: function (response) {
                            if(! response.code)
                            {
                                 alert(response.msg.phone)
                                 $phoneEle.val('')
                            }
                            else{
                                alert('验证码发送成功！')
                            }
                        }
                }
                )
            }
        )

        $submitBtn.click(function (e){
            $.ajax({
                url:'/smslogin/',
                type: 'post',
                data: $registerForm.serialize(),
                success:function (res){
                    if(res.code===1)
                    {
                        location.href=res.url
                    }
                    else
                    {
                        if (res.msg.code)
                        {
                           alert(res.msg.code)
                        }
                        else
                        {
                            alert(res.msg.phone)
                        }
                    }
                }
            })
        })

        $('input').click(function (){
            $(this).next().text('').parent().removeClass('has-error')
        })
    </script>
{% endblock %}

web/templates/order.html
{% extends 'bases/base.html' %}

{% block content %}
    <div class="container">
        <div>
            <h1>订单</h1>
            <table class="table table-bordered table-striped table-hover">
                <thead>
                <tr>
                    <th>订单号</th>
                    <th>单价</th>
                    <th>数量</th>
                    <th>折扣</th>
                    <th>实际支付</th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ order_dic.out_trade_no }}</td>
                        <td>{{ order_dic.single_price}}</td>
                        <td>{{ order_dic.count }}</td>
                        <td>无</td>
                        <td>{{ order_dic.price }}</td>
                    </tr>
                </tbody>
            </table>
            <button class="btn btn-default" id="sure">确认支付</button>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $('#sure').click(function (){
            $.ajax({
                url:"{% url 'order' %}",
                type:'post',
                dataType:'json',
                success:function (res){
                    if (res.code)
                    {
                        location.href=res.url
                    }
                    else
                    {
                        alert(res.msg)
                    }
                }
            })
        })
    </script>
{% endblock %}

web/templates/pay.html
{% extends 'bases/base.html' %}



{% block content %}
    <h1 class="text-center h1" style="margin-top: 100px">多种方案，使用多种场景</h1>
    <div class="container" style="margin-top: 100px">
        <div class="row">
            {% for price in prices %}
            <div class="col-md-4">
                <div class="panel panel-default">
                  <div class="panel-heading">{{ price.title }}</div>
                  <div class="panel-body">
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <td>
                                    <h2 class="text-center">￥<span>{{ price.price }}</span>/年</h2>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <form action="{% url 'pay' %}" method="post">
                                        {% csrf_token %}
                                        <input type="text" hidden name="pid" value="{{ price.id }}">
                                        <div class="input-group">
                                            <span class="input-group-addon" id="basic-addon1">数量</span>
                                              <input type="text" class="form-control" placeholder="购买数量" aria-describedby="basic-addon1" value="1" name="count">
                                                <div class="input-group-btn">
                                                    <button class="btn btn-success" type="submit">立即购买</button>
                                              </div>
                                    </div>
                                    </form>
                                </td>
                            </tr>
                            <tr>
                                <td>最大项目数量:{{ price.project_num }}</td>
                            </tr>
                        <tr>
                            <td>最大项目空间:{{ price.project_space }}</td>
                        </tr>
                        <tr>
                            <td>最大文件支持:{{ price.per_file_size }}</td>
                        </tr>
                        <tr>
                            <td>项目成员:{{ price.project_member }}</td>
                        </tr>
                        </tbody>
                    </table>
                  </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

web/templates/pay_failed.html
{% extends 'bases/base.html' %}



{% block content %}
    <div class="container">
        <h1>支付失败</h1>
        <h2>订单号：{{ out_trade_no }}</h2>
    </div>
{% endblock %}